exports.el = {
    continueButton: '.continue > .optionone > .button',
    nomeSegurado: '.row-segurados > :nth-child(1) > input',
    nascimentoSegurado: '.row-segurados > :nth-child(2) > input',
    cpfSegurado: '.row-segurados > :nth-child(3) > input',
    cartaoCredito: '#cartao-credito',
    boleto: '#boleto',
    transferirInfos: '.transfer-infos',
    nomeContato: '.gcontato > input',
    emailContato: '.gemail > .desktop',
    telefoneContato: '.g-telefone > input',
    cepContato: '.gcep > input',
    numeroContato: '.gnumero > input',
    complementoContato: '.gcomplemento > input',
    selecioneEstadoContato: '.selectstate',
    efetuarPagamento: '.finish-payment',
    masterCard: '#card2',
    cartao: '#cc-number',
    nomeCartao: '#cc-holder-name',
    cpfCartao: '#cc-holder-cpf',
    mesCartao: '#cc-expiry-month',
    anoCartao: '#cc-expiry-year',
    cvvCartao: '#cc-verfication-code',
    parcelamentoCartao: ':nth-child(1) > .label-form',
    cupom: '#cupom',
    buttonCupom: '.cupom-desconto > button'
}; 