exports.el = {
    continueButton: '.continue > .optionone > .button',
    nomeSegurado: '.row-segurados > :nth-child(1) > input',
    nascimentoSegurado: '.row-segurados > :nth-child(2) > input',
    cpfSegurado: '.row-segurados > :nth-child(3) > input',
    cartãoCrédito: '#cartao-credito',
    boleto: '#boleto',
    transferirInfos: '.transfer-infos',
    nomeContato: '.gcontato > input',
    emailContato: '.gemail > .desktop',
    telefoneContato: '.g-telefone > input',
    cepContato: '.gcep > input',
    númeroContato: '.gnumero > input',
    complementoContato: '.gcomplemento > input',
    selecioneEstadoContato: '.selectstate',
    efetuarPagamento: '.finish-payment',
    masterCard: '#card2',
    cartão: '#cc-number',
    nomeCartão: '#cc-holder-name',
    cpfCartão: '#cc-holder-cpf',
    mêsCartão: '#cc-expiry-month',
    anoCartão: '#cc-expiry-year',
    cvvCartão: '#cc-verfication-code',
    parcelamentoCartão: ':nth-child(1) > .label-form',
    cupom: '#cupom',
    buttonCupom: '.cupom-desconto > button'
}; 